/*
 * FIRST Tech Challenge Vortex Counter
 * Created by Alexander Fera
 * Fera Group
 * Novi, MI 48377{licensePrefix}
 */
package ftc.goal.counter;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author afera
 */
public class AudDisplayGreen1280 extends javax.swing.JFrame {

    /**
     * Creates new form AudDisplay
     */
    public AudDisplayGreen1280() {
        initComponents();
        Image img = new ImageIcon(getClass().getResource(GoalCounterUI.iconURL)).getImage();
        setIconImage(img);
        getContentPane().setBackground(Color.WHITE);
        jPanel1.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        BlueCorAutoDisplay = new javax.swing.JLabel();
        BlueCenTeleDisplay = new javax.swing.JLabel();
        RedCorAutoDisplay = new javax.swing.JLabel();
        RedCorTeleDisplay = new javax.swing.JLabel();
        BlueCenAutoDisplay = new javax.swing.JLabel();
        RedCenTeleDisplay = new javax.swing.JLabel();
        RedCenAutoDisplay = new javax.swing.JLabel();
        BlueCorTeleDisplay = new javax.swing.JLabel();
        lowerThirdBG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Keyable Display");
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1280, 718));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0};
        layout.columnWeights = new double[] {0.0};
        layout.rowWeights = new double[] {0.0};
        getContentPane().setLayout(layout);

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        BlueCorAutoDisplay.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        BlueCorAutoDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BlueCorAutoDisplay.setText("0");
        jPanel1.add(BlueCorAutoDisplay);
        BlueCorAutoDisplay.setBounds(20, 650, 100, 60);

        BlueCenTeleDisplay.setFont(new java.awt.Font("Arial", 1, 70)); // NOI18N
        BlueCenTeleDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BlueCenTeleDisplay.setText("0");
        jPanel1.add(BlueCenTeleDisplay);
        BlueCenTeleDisplay.setBounds(150, 560, 140, 60);

        RedCorAutoDisplay.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        RedCorAutoDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RedCorAutoDisplay.setText("0");
        jPanel1.add(RedCorAutoDisplay);
        RedCorAutoDisplay.setBounds(1160, 560, 100, 60);

        RedCorTeleDisplay.setFont(new java.awt.Font("Arial", 1, 70)); // NOI18N
        RedCorTeleDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RedCorTeleDisplay.setText("0");
        jPanel1.add(RedCorTeleDisplay);
        RedCorTeleDisplay.setBounds(990, 650, 150, 60);

        BlueCenAutoDisplay.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        BlueCenAutoDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BlueCenAutoDisplay.setText("0");
        jPanel1.add(BlueCenAutoDisplay);
        BlueCenAutoDisplay.setBounds(20, 560, 100, 60);

        RedCenTeleDisplay.setFont(new java.awt.Font("Arial", 1, 70)); // NOI18N
        RedCenTeleDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RedCenTeleDisplay.setText("0");
        jPanel1.add(RedCenTeleDisplay);
        RedCenTeleDisplay.setBounds(990, 560, 150, 60);

        RedCenAutoDisplay.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        RedCenAutoDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RedCenAutoDisplay.setText("0");
        RedCenAutoDisplay.setMaximumSize(new java.awt.Dimension(186, 180));
        RedCenAutoDisplay.setMinimumSize(new java.awt.Dimension(186, 180));
        jPanel1.add(RedCenAutoDisplay);
        RedCenAutoDisplay.setBounds(1160, 650, 100, 60);

        BlueCorTeleDisplay.setFont(new java.awt.Font("Arial", 1, 70)); // NOI18N
        BlueCorTeleDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BlueCorTeleDisplay.setText("0");
        jPanel1.add(BlueCorTeleDisplay);
        BlueCorTeleDisplay.setBounds(150, 650, 140, 60);

        lowerThirdBG.setForeground(new java.awt.Color(255, 255, 255));
        lowerThirdBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/lowerThird3.jpg"))); // NOI18N
        lowerThirdBG.setRequestFocusEnabled(false);
        jPanel1.add(lowerThirdBG);
        lowerThirdBG.setBounds(0, 550, 1280, 172);

        jLabel1.setBackground(new java.awt.Color(51, 255, 0));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 550);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        SettingsUI.toggleFullscreen.setEnabled(false);
        SettingsUI.toggleFullscreen.setToolTipText("You need to open the Audience display first");
        GoalCounterUI.auddisplay.setEnabled(true);
        GoalCounterUI.audIsOpen = false;
        SettingsUI.jComboBox1.setEnabled(true);
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        SettingsUI.toggleFullscreen.setEnabled(true);
        SettingsUI.toggleFullscreen.setToolTipText("Toggle Full Screen mode for the Audience Display");
        GoalCounterUI.auddisplay.setEnabled(false);
        GoalCounterUI.audIsOpen = true;
        SettingsUI.jComboBox1.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        SettingsUI.toggleFullscreen.setEnabled(true);
        SettingsUI.toggleFullscreen.setToolTipText("Toggle Full Screen mode for the Audience Display");
        GoalCounterUI.auddisplay.setEnabled(false);
        GoalCounterUI.audIsOpen = true;
        SettingsUI.jComboBox1.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int key = evt.getKeyCode();
        if(key == KeyEvent.VK_ESCAPE){
            SettingsUI.exitFullscreen();
        }else if(key == KeyEvent.VK_F5){
            SettingsUI.toggleFullscreen();
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AudDisplayGreen1280.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AudDisplayGreen1280.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AudDisplayGreen1280.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AudDisplayGreen1280.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AudDisplayGreen1280().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel BlueCenAutoDisplay;
    public static javax.swing.JLabel BlueCenTeleDisplay;
    public static javax.swing.JLabel BlueCorAutoDisplay;
    public static javax.swing.JLabel BlueCorTeleDisplay;
    public static javax.swing.JLabel RedCenAutoDisplay;
    public static javax.swing.JLabel RedCenTeleDisplay;
    public static javax.swing.JLabel RedCorAutoDisplay;
    public static javax.swing.JLabel RedCorTeleDisplay;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lowerThirdBG;
    // End of variables declaration//GEN-END:variables
}
