/*
 * FIRST Tech Challenge Vortex Counter
 * Created by Alexander Fera
 * Fera Group
 * Novi, MI 48377{licensePrefix}
 */
package ftc.goal.counter;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author afera
 */
public class AudDisplay1280 extends javax.swing.JFrame {

    /**
     * Creates new form AudDisplay
     */
    public AudDisplay1280() {
        initComponents();
        Image img = new ImageIcon(getClass().getResource(GoalCounterUI.iconURL)).getImage();
        setIconImage(img);
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        BlueCorAutoDisplay = new javax.swing.JLabel();
        BlueCenTeleDisplay = new javax.swing.JLabel();
        RedCorAutoDisplay = new javax.swing.JLabel();
        RedCorTeleDisplay = new javax.swing.JLabel();
        BlueCenAutoDisplay = new javax.swing.JLabel();
        RedCenTeleDisplay = new javax.swing.JLabel();
        RedCenAutoDisplay = new javax.swing.JLabel();
        BlueCorTeleDisplay = new javax.swing.JLabel();
        RedCenJSRed = new javax.swing.JLabel();
        RedCenJSOrange = new javax.swing.JLabel();
        RedCenJSGreen = new javax.swing.JLabel();
        RedCorJSRed = new javax.swing.JLabel();
        RedCorJSOrange = new javax.swing.JLabel();
        RedCorJSGreen = new javax.swing.JLabel();
        BlueCenJSRed = new javax.swing.JLabel();
        BlueCenJSOrange = new javax.swing.JLabel();
        BlueCenJSGreen = new javax.swing.JLabel();
        BlueCorJSRed = new javax.swing.JLabel();
        BlueCorJSOrange = new javax.swing.JLabel();
        BlueCorJSGreen = new javax.swing.JLabel();
        TimerDisplay = new javax.swing.JLabel();
        State = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0};
        layout.columnWeights = new double[] {0.0};
        layout.rowWeights = new double[] {0.0};
        getContentPane().setLayout(layout);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(null);

        BlueCorAutoDisplay.setFont(new java.awt.Font("Arial", 0, 125)); // NOI18N
        BlueCorAutoDisplay.setForeground(new java.awt.Color(255, 255, 255));
        BlueCorAutoDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BlueCorAutoDisplay.setText("0");
        jPanel1.add(BlueCorAutoDisplay);
        BlueCorAutoDisplay.setBounds(10, 470, 140, 170);

        BlueCenTeleDisplay.setFont(new java.awt.Font("Arial", 1, 125)); // NOI18N
        BlueCenTeleDisplay.setForeground(new java.awt.Color(255, 255, 255));
        BlueCenTeleDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BlueCenTeleDisplay.setText("0");
        jPanel1.add(BlueCenTeleDisplay);
        BlueCenTeleDisplay.setBounds(170, 240, 200, 170);

        RedCorAutoDisplay.setFont(new java.awt.Font("Arial", 0, 125)); // NOI18N
        RedCorAutoDisplay.setForeground(new java.awt.Color(255, 255, 255));
        RedCorAutoDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RedCorAutoDisplay.setText("0");
        jPanel1.add(RedCorAutoDisplay);
        RedCorAutoDisplay.setBounds(1130, 470, 140, 180);

        RedCorTeleDisplay.setFont(new java.awt.Font("Arial", 1, 125)); // NOI18N
        RedCorTeleDisplay.setForeground(new java.awt.Color(255, 255, 255));
        RedCorTeleDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RedCorTeleDisplay.setText("0");
        jPanel1.add(RedCorTeleDisplay);
        RedCorTeleDisplay.setBounds(910, 470, 200, 180);

        BlueCenAutoDisplay.setFont(new java.awt.Font("Arial", 0, 125)); // NOI18N
        BlueCenAutoDisplay.setForeground(new java.awt.Color(255, 255, 255));
        BlueCenAutoDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BlueCenAutoDisplay.setText("0");
        jPanel1.add(BlueCenAutoDisplay);
        BlueCenAutoDisplay.setBounds(10, 240, 140, 170);

        RedCenTeleDisplay.setFont(new java.awt.Font("Arial", 1, 125)); // NOI18N
        RedCenTeleDisplay.setForeground(new java.awt.Color(255, 255, 255));
        RedCenTeleDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RedCenTeleDisplay.setText("0");
        jPanel1.add(RedCenTeleDisplay);
        RedCenTeleDisplay.setBounds(910, 240, 200, 170);

        RedCenAutoDisplay.setFont(new java.awt.Font("Arial", 0, 125)); // NOI18N
        RedCenAutoDisplay.setForeground(new java.awt.Color(255, 255, 255));
        RedCenAutoDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RedCenAutoDisplay.setText("0");
        RedCenAutoDisplay.setMaximumSize(new java.awt.Dimension(186, 180));
        RedCenAutoDisplay.setMinimumSize(new java.awt.Dimension(186, 180));
        jPanel1.add(RedCenAutoDisplay);
        RedCenAutoDisplay.setBounds(1130, 240, 140, 170);

        BlueCorTeleDisplay.setFont(new java.awt.Font("Arial", 1, 125)); // NOI18N
        BlueCorTeleDisplay.setForeground(new java.awt.Color(255, 255, 255));
        BlueCorTeleDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BlueCorTeleDisplay.setText("0");
        jPanel1.add(BlueCorTeleDisplay);
        BlueCorTeleDisplay.setBounds(170, 470, 200, 180);

        RedCenJSRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/ControllerRedMedium.png"))); // NOI18N
        jPanel1.add(RedCenJSRed);
        RedCenJSRed.setBounds(920, 160, 80, 80);

        RedCenJSOrange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/ControllerOrangeMedium.png"))); // NOI18N
        jPanel1.add(RedCenJSOrange);
        RedCenJSOrange.setBounds(920, 160, 80, 80);

        RedCenJSGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/ControllerGreenMedium.png"))); // NOI18N
        jPanel1.add(RedCenJSGreen);
        RedCenJSGreen.setBounds(920, 160, 80, 80);

        RedCorJSRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/ControllerRedMedium.png"))); // NOI18N
        jPanel1.add(RedCorJSRed);
        RedCorJSRed.setBounds(1070, 650, 80, 70);

        RedCorJSOrange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/ControllerOrangeMedium.png"))); // NOI18N
        jPanel1.add(RedCorJSOrange);
        RedCorJSOrange.setBounds(1070, 650, 80, 70);

        RedCorJSGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/ControllerGreenMedium.png"))); // NOI18N
        jPanel1.add(RedCorJSGreen);
        RedCorJSGreen.setBounds(1070, 650, 80, 70);

        BlueCenJSRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/ControllerRedMedium.png"))); // NOI18N
        jPanel1.add(BlueCenJSRed);
        BlueCenJSRed.setBounds(290, 160, 80, 80);

        BlueCenJSOrange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/ControllerOrangeMedium.png"))); // NOI18N
        jPanel1.add(BlueCenJSOrange);
        BlueCenJSOrange.setBounds(290, 160, 80, 80);

        BlueCenJSGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/ControllerGreenMedium.png"))); // NOI18N
        jPanel1.add(BlueCenJSGreen);
        BlueCenJSGreen.setBounds(290, 160, 80, 80);

        BlueCorJSRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/ControllerRedMedium.png"))); // NOI18N
        jPanel1.add(BlueCorJSRed);
        BlueCorJSRed.setBounds(110, 650, 80, 70);

        BlueCorJSOrange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/ControllerOrangeMedium.png"))); // NOI18N
        jPanel1.add(BlueCorJSOrange);
        BlueCorJSOrange.setBounds(110, 650, 80, 70);

        BlueCorJSGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/ControllerGreenMedium.png"))); // NOI18N
        jPanel1.add(BlueCorJSGreen);
        BlueCorJSGreen.setBounds(110, 650, 80, 70);

        TimerDisplay.setFont(new java.awt.Font("Dialog", 1, 250)); // NOI18N
        TimerDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimerDisplay.setText("2:30");
        jPanel1.add(TimerDisplay);
        TimerDisplay.setBounds(1, 0, 1290, 230);

        State.setFont(new java.awt.Font("Arial", 1, 65)); // NOI18N
        State.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        State.setText("Autonomous Mode");
        jPanel1.add(State);
        State.setBounds(0, 640, 1280, 80);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/AudDispBackground1280p.png"))); // NOI18N
        background.setOpaque(true);
        jPanel1.add(background);
        background.setBounds(0, 0, 1280, 720);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 48, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        SettingsUI.toggleFullscreen.setEnabled(false);
        SettingsUI.toggleFullscreen.setToolTipText("You need to open the Audience display first");
        GoalCounterUI.auddisplay.setEnabled(true);
        GoalCounterUI.audIsOpen = false;
        SettingsUI.jComboBox1.setEnabled(true);
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        SettingsUI.toggleFullscreen.setEnabled(true);
        SettingsUI.toggleFullscreen.setToolTipText("Toggle Full Screen mode for the Audience Display");
        GoalCounterUI.auddisplay.setEnabled(false);
        GoalCounterUI.audIsOpen = true;
        SettingsUI.jComboBox1.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        SettingsUI.toggleFullscreen.setEnabled(true);
        SettingsUI.toggleFullscreen.setToolTipText("Toggle Full Screen mode for the Audience Display");
        GoalCounterUI.auddisplay.setEnabled(false);
        GoalCounterUI.audIsOpen = true;
        SettingsUI.jComboBox1.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int key = evt.getKeyCode();
        if(key == KeyEvent.VK_ESCAPE){
            SettingsUI.exitFullscreen();
        }else if(key == KeyEvent.VK_F5){
            SettingsUI.toggleFullscreen();
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AudDisplay1280.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AudDisplay1280.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AudDisplay1280.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AudDisplay1280.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AudDisplay1280().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel BlueCenAutoDisplay;
    public static javax.swing.JLabel BlueCenJSGreen;
    public static javax.swing.JLabel BlueCenJSOrange;
    public static javax.swing.JLabel BlueCenJSRed;
    public static javax.swing.JLabel BlueCenTeleDisplay;
    public static javax.swing.JLabel BlueCorAutoDisplay;
    public static javax.swing.JLabel BlueCorJSGreen;
    public static javax.swing.JLabel BlueCorJSOrange;
    public static javax.swing.JLabel BlueCorJSRed;
    public static javax.swing.JLabel BlueCorTeleDisplay;
    public static javax.swing.JLabel RedCenAutoDisplay;
    public static javax.swing.JLabel RedCenJSGreen;
    public static javax.swing.JLabel RedCenJSOrange;
    public static javax.swing.JLabel RedCenJSRed;
    public static javax.swing.JLabel RedCenTeleDisplay;
    public static javax.swing.JLabel RedCorAutoDisplay;
    public static javax.swing.JLabel RedCorJSGreen;
    public static javax.swing.JLabel RedCorJSOrange;
    public static javax.swing.JLabel RedCorJSRed;
    public static javax.swing.JLabel RedCorTeleDisplay;
    public static javax.swing.JLabel State;
    public static javax.swing.JLabel TimerDisplay;
    public static javax.swing.JLabel background;
    public static javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
