/*
 * FIRST Tech Challenge Vortex Counter
 * Created by Alexander Fera
 * Fera Group
 * Novi, MI 48377{licensePrefix}
 */
package ftc.goal.counter;


/**
 *
 * @author afera
 */
public class ViewJSConfig extends javax.swing.JFrame {

    /**
     * Creates new form AudDisplay
     */
    public ViewJSConfig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ResetEverything1 = new javax.swing.JLabel();
        xToggleModes = new javax.swing.JLabel();
        ResetEverything = new javax.swing.JLabel();
        rbRedCenter = new javax.swing.JLabel();
        rbRedCorner = new javax.swing.JLabel();
        rbBlueCenter = new javax.swing.JLabel();
        rbBlueCorner = new javax.swing.JLabel();
        aRedCenter = new javax.swing.JLabel();
        aRedCorner = new javax.swing.JLabel();
        aBlueCenter = new javax.swing.JLabel();
        aBlueCorner = new javax.swing.JLabel();
        lbRedCenter = new javax.swing.JLabel();
        lbRedCorner = new javax.swing.JLabel();
        lbBlueCenter = new javax.swing.JLabel();
        lbBlueCorner = new javax.swing.JLabel();
        ResetEverything2 = new javax.swing.JLabel();
        ResetEverything3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.setLayout(null);

        ResetEverything1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResetEverything1.setText("Timer Controller");
        jPanel1.add(ResetEverything1);
        ResetEverything1.setBounds(320, 60, 110, 20);

        xToggleModes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xToggleModes.setText("Can be used on Timer Controller");
        jPanel1.add(xToggleModes);
        xToggleModes.setBounds(170, 350, 220, 17);

        ResetEverything.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResetEverything.setText("Can be used on");
        jPanel1.add(ResetEverything);
        ResetEverything.setBounds(320, 40, 110, 20);

        rbRedCenter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbRedCenter.setText("Asigned to Red Center");
        rbRedCenter.setEnabled(false);
        jPanel1.add(rbRedCenter);
        rbRedCenter.setBounds(420, 120, 140, 20);

        rbRedCorner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbRedCorner.setText("Asigned to Red Corner");
        rbRedCorner.setEnabled(false);
        jPanel1.add(rbRedCorner);
        rbRedCorner.setBounds(420, 140, 140, 20);

        rbBlueCenter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbBlueCenter.setText("Asigned to Blue Center");
        rbBlueCenter.setEnabled(false);
        jPanel1.add(rbBlueCenter);
        rbBlueCenter.setBounds(420, 160, 140, 20);

        rbBlueCorner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbBlueCorner.setText("Asigned to Blue Corner");
        rbBlueCorner.setEnabled(false);
        jPanel1.add(rbBlueCorner);
        rbBlueCorner.setBounds(420, 180, 140, 20);

        aRedCenter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aRedCenter.setText("Asigned to Red Center");
        jPanel1.add(aRedCenter);
        aRedCenter.setBounds(440, 280, 150, 20);

        aRedCorner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aRedCorner.setText("Asigned to Red Corner");
        jPanel1.add(aRedCorner);
        aRedCorner.setBounds(440, 300, 150, 20);

        aBlueCenter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aBlueCenter.setText("Asigned to Blue Center");
        jPanel1.add(aBlueCenter);
        aBlueCenter.setBounds(440, 320, 150, 20);

        aBlueCorner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aBlueCorner.setText("Asigned to Blue Corner");
        jPanel1.add(aBlueCorner);
        aBlueCorner.setBounds(440, 340, 160, 20);

        lbRedCenter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbRedCenter.setText("Asigned to Red Center");
        lbRedCenter.setEnabled(false);
        jPanel1.add(lbRedCenter);
        lbRedCenter.setBounds(0, 140, 160, 20);

        lbRedCorner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbRedCorner.setText("Asigned to Red Corner");
        lbRedCorner.setEnabled(false);
        jPanel1.add(lbRedCorner);
        lbRedCorner.setBounds(0, 160, 160, 20);

        lbBlueCenter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbBlueCenter.setText("Asigned to Blue Center");
        lbBlueCenter.setEnabled(false);
        jPanel1.add(lbBlueCenter);
        lbBlueCenter.setBounds(0, 180, 160, 20);

        lbBlueCorner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbBlueCorner.setText("Asigned to Blue Corner");
        lbBlueCorner.setEnabled(false);
        jPanel1.add(lbBlueCorner);
        lbBlueCorner.setBounds(0, 200, 160, 20);

        ResetEverything2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResetEverything2.setText("Timer Controller");
        jPanel1.add(ResetEverything2);
        ResetEverything2.setBounds(210, 110, 110, 17);

        ResetEverything3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResetEverything3.setText("Can be used on");
        jPanel1.add(ResetEverything3);
        ResetEverything3.setBounds(210, 90, 110, 17);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ftc/goal/counter/images/ControllerMap.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(40, 0, 500, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewJSConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewJSConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewJSConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewJSConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewJSConfig().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ResetEverything;
    private javax.swing.JLabel ResetEverything1;
    private javax.swing.JLabel ResetEverything2;
    private javax.swing.JLabel ResetEverything3;
    public static javax.swing.JLabel aBlueCenter;
    public static javax.swing.JLabel aBlueCorner;
    public static javax.swing.JLabel aRedCenter;
    public static javax.swing.JLabel aRedCorner;
    private javax.swing.JLabel background;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lbBlueCenter;
    public static javax.swing.JLabel lbBlueCorner;
    public static javax.swing.JLabel lbRedCenter;
    public static javax.swing.JLabel lbRedCorner;
    public static javax.swing.JLabel rbBlueCenter;
    public static javax.swing.JLabel rbBlueCorner;
    public static javax.swing.JLabel rbRedCenter;
    public static javax.swing.JLabel rbRedCorner;
    public static javax.swing.JLabel xToggleModes;
    // End of variables declaration//GEN-END:variables
}
